In [2]:
import pandas as pd
df = pd.read_csv('laptops.csv')
df.head()

,Company,TypeName,Inches,screen_resolution,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_brand,cpu_name,cpu_speed,Ram,memory_type,primary_storage,gpu_brand,gpu_name,OpSys,Weight,Price,total_pixels
0,NaN,Ultrabook,13.3,NaN,1,0,1600.0,2560,Intel,Core i5,2.3,8.0,SSD,128,Intel,Iris Plus Graphics 640,NaN,1.4,71379,4096000
1,Apple,Ultrabook,13.3,NaN,0,0,900.0,1440,Intel,Core i5,1.8,8.0,NaN,128,Intel,HD Graphics 6000,macos,1.3,47896,1296000
2,HP,Notebook,15.6,Full HD,0,0,1080.0,1920,Intel,Core i5,2.5,8.0,NaN,256,Intel,HD Graphics 620,NaN,1.9,30636,2073600
3,Apple,Ultrabook,15.4,NaN,1,0,1800.0,2880,Intel,Core i7,2.7,16.0,NaN,512,AMD,Radeon Pro 455,macos,1.8,135195,5184000
4,Apple,Ultrabook,13.3,NaN,1,0,1600.0,2560,Intel,Core i5,3.1,8.0,SSD,256,Intel,Iris Plus Graphics 650,macos,1.4,96096,4096000

 Question 1

Without doing any cleaning, answer the question below:

How many columns does this data set have?

 Question 2

Without doing any cleaning, answer the question below:

How many columns contain at least one null value?

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1322 entries, 0 to 1321
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1189 non-null   object
 1   TypeName           1322 non-null   object
 2   Inches             1322 non-null   float64
 3   screen_resolution  930 non-null    object
 4   has_ips_panel      1322 non-null   int64
 5   is_touchscreen     1322 non-null   int64
 6   resolution_width   1216 non-null   float64
 7   resolution_height  1322 non-null   int64
 8   cpu_brand          1322 non-null   object
 9   cpu_name           1322 non-null   object
 10  cpu_speed          1322 non-null   float64
 11  Ram                1243 non-null   float64
 12  memory_type        390 non-null    object
 13  primary_storage    1322 non-null   int64
 14  gpu_brand          1322 non-null   object
 15  gpu_name           1322 non-null   object
 16  OpSys              1133 non-null   object
 17  Weight             1249 non-null   float64
 18  Price              1322 non-null   int64
 19  total_pixels       1322 non-null   int64
dtypes: float64(5), int64(6), object(9)
memory usage: 206.7+ KB

 Question 3

Use data cleaning techniques to drop all rows from the data set if they contain a null value in at least one column.

How many rows are left?

In [4]:
df.dropna()

,Company,TypeName,Inches,screen_resolution,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_brand,cpu_name,cpu_speed,Ram,memory_type,primary_storage,gpu_brand,gpu_name,OpSys,Weight,Price,total_pixels
9,Acer,Ultrabook,14.0,Full HD,1,0,1080.0,1920,Intel,Core i5,1.6,20.0,SSD,256,Intel,UHD Graphics 620,windows,1.6,41026,2073600
20,Lenovo,Gaming,15.6,Full HD,1,0,1080.0,1920,Intel,Core i5,2.5,20.0,Hybrid,128,Nvidia,GeForce GTX 1050,windows,2.5,53227,2073600
22,Dell,2 in 1 Convertible,13.3,Full HD,0,1,1080.0,1920,Intel,Core i5,1.6,20.0,SSD,256,Intel,UHD Graphics 620,windows,1.6,43636,2073600
26,Dell,Notebook,15.6,Full HD,0,0,1080.0,1920,Intel,Core i5,1.6,8.0,SSD,256,AMD,Radeon 530,windows,2.2,42624,2073600
32,dell,Ultrabook,13.3,Quad HD +,0,1,1800.0,3200,Intel,Core i7,1.8,16.0,SSD,512,Intel,UHD Graphics 620,windows,1.2,99580,5760000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1294,dell,Ultrabook,12.5,Full HD,0,0,1080.0,1920,Intel,Core i7,2.8,8.0,SSD,256,Intel,HD Graphics 620,windows,1.6,90043,2073600
1300,lenovo,Notebook,15.6,Full HD,0,0,1080.0,1920,AMD,A12-Series 9720P,3.6,12.0,SSD,512,AMD,Radeon 530,windows,2.2,50563,2073600
1303,lenovo,Notebook,14.0,Full HD,1,0,1080.0,1920,Intel,Core i5,2.6,8.0,SSD,256,Intel,HD Graphics 620,windows,1.3,87912,2073600
1305,HP,Notebook,17.3,Full HD,0,0,1080.0,1920,Intel,Core i7,2.7,8.0,SSD,256,Nvidia,GeForce 930MX,windows,2.6,63936,2073600
1314,Lenovo,Notebook,13.3,Full HD,1,0,1080.0,1920,Intel,Core i5,2.5,8.0,SSD,-256,Intel,HD Graphics 620,windows,1.1,53227,2073600

 Question 4

Re-import the data set before continuing.

Which column has the most null values?

In [5]:
df = pd.read_csv('laptops.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1322 entries, 0 to 1321
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            1189 non-null   object
 1   TypeName           1322 non-null   object
 2   Inches             1322 non-null   float64
 3   screen_resolution  930 non-null    object
 4   has_ips_panel      1322 non-null   int64
 5   is_touchscreen     1322 non-null   int64
 6   resolution_width   1216 non-null   float64
 7   resolution_height  1322 non-null   int64
 8   cpu_brand          1322 non-null   object
 9   cpu_name           1322 non-null   object
 10  cpu_speed          1322 non-null   float64
 11  Ram                1243 non-null   float64
 12  memory_type        390 non-null    object
 13  primary_storage    1322 non-null   int64
 14  gpu_brand          1322 non-null   object
 15  gpu_name           1322 non-null   object
 16  OpSys              1133 non-null   object
 17  Weight             1249 non-null   float64
 18  Price              1322 non-null   int64
 19  total_pixels       1322 non-null   int64
dtypes: float64(5), int64(6), object(9)
memory usage: 206.7+ KB

 Question 5

Compute descriptive statistics on all numerical columns in the data set. Which of the following issues stand out to you in terms of violating business logic rules?

If you aren't sure what the names of the columns mean, Google them (ie. "what is laptop Ram").

In [8]:
df.describe()

,Inches,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_speed,Ram,primary_storage,Weight,Price,total_pixels
count,1322.000000,1322.000000,1322.000000,1216.000000,1322.000000,1322.000000,1243.000000,1322.000000,1249.000000,1.322000e+03,1.322000e+03
mean,15.122542,0.281392,0.146747,1074.299342,1895.639939,2.301664,9.198713,396.865356,2.078383,5.838318e+04,2.170972e+06
std,1.945084,0.449848,0.353988,286.711732,494.741031,0.507130,7.031441,419.775480,0.796887,5.045083e+04,1.393255e+06
min,10.100000,0.000000,0.000000,768.000000,1366.000000,0.900000,1.000000,-2048.000000,0.000000,-1.427900e+05,1.049088e+06
25%,14.000000,0.000000,0.000000,900.000000,1600.000000,2.000000,4.000000,256.000000,1.500000,3.118475e+04,1.440000e+06
50%,15.600000,0.000000,0.000000,1080.000000,1920.000000,2.500000,8.000000,256.000000,2.000000,5.109600e+04,2.073600e+06
75%,15.600000,1.000000,0.000000,1080.000000,1920.000000,2.700000,8.000000,512.000000,2.300000,7.863225e+04,2.073600e+06
max,35.600000,1.000000,1.000000,2160.000000,3840.000000,3.600000,80.000000,2048.000000,11.100000,1.016580e+06,8.294400e+06

 Question 6

Fix the business logic errors by changing all of the negative values in the columns identified above to positive values.

After performing the cleaning step above, what is the average amount of primary storage in a laptop in the data set?

 Question 7

After performing the cleaning step above, what is the average price of a laptop in the data set?

Note that amounts are not listed in USD.

In [9]:
df[df[['primary_storage', 'Price']] < 0] *= -1

In [10]:
df.describe()

,Inches,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_speed,Ram,primary_storage,Weight,Price,total_pixels
count,1322.000000,1322.000000,1322.000000,1216.000000,1322.000000,1322.000000,1243.000000,1322.000000,1249.000000,1.322000e+03,1.322000e+03
mean,15.122542,0.281392,0.146747,1074.299342,1895.639939,2.301664,9.198713,447.582451,2.078383,6.101401e+04,2.170972e+06
std,1.945084,0.449848,0.353988,286.711732,494.741031,0.507130,7.031441,365.172689,0.796887,4.723277e+04,1.393255e+06
min,10.100000,0.000000,0.000000,768.000000,1366.000000,0.900000,1.000000,0.000000,0.000000,9.271000e+03,1.049088e+06
25%,14.000000,0.000000,0.000000,900.000000,1600.000000,2.000000,4.000000,256.000000,1.500000,3.192700e+04,1.440000e+06
50%,15.600000,0.000000,0.000000,1080.000000,1920.000000,2.500000,8.000000,256.000000,2.000000,5.216100e+04,2.073600e+06
75%,15.600000,1.000000,0.000000,1080.000000,1920.000000,2.700000,8.000000,512.000000,2.300000,7.937350e+04,2.073600e+06
max,35.600000,1.000000,1.000000,2160.000000,3840.000000,3.600000,80.000000,2048.000000,11.100000,1.016580e+06,8.294400e+06

Question 8 

Impute the missing values in the resolution width column by dividing the total pixels by the resolution height.

After performing the cleaning step above, what is the average resolution width of a laptop?

In [11]:
df['resolution_width'] = df['resolution_width'].fillna(df['total_pixels'] / df['resolution_height'])

In [12]:
df.describe()

,Inches,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_speed,Ram,primary_storage,Weight,Price,total_pixels
count,1322.000000,1322.000000,1322.000000,1322.000000,1322.000000,1322.000000,1243.000000,1322.000000,1249.000000,1.322000e+03,1.322000e+03
mean,15.122542,0.281392,0.146747,1071.428139,1895.639939,2.301664,9.198713,447.582451,2.078383,6.101401e+04,2.170972e+06
std,1.945084,0.449848,0.353988,284.746319,494.741031,0.507130,7.031441,365.172689,0.796887,4.723277e+04,1.393255e+06
min,10.100000,0.000000,0.000000,768.000000,1366.000000,0.900000,1.000000,0.000000,0.000000,9.271000e+03,1.049088e+06
25%,14.000000,0.000000,0.000000,900.000000,1600.000000,2.000000,4.000000,256.000000,1.500000,3.192700e+04,1.440000e+06
50%,15.600000,0.000000,0.000000,1080.000000,1920.000000,2.500000,8.000000,256.000000,2.000000,5.216100e+04,2.073600e+06
75%,15.600000,1.000000,0.000000,1080.000000,1920.000000,2.700000,8.000000,512.000000,2.300000,7.937350e+04,2.073600e+06
max,35.600000,1.000000,1.000000,2160.000000,3840.000000,3.600000,80.000000,2048.000000,11.100000,1.016580e+06,8.294400e+06

 Question 9

Note the number of null values in the memory_type column of the data set. Given that this column contains many null values and is relatively unimportant to the analysis, what do you recommend doing?

In [13]:
df.drop(columns=['memory_type'], inplace=True)

 Question 10

Perform the operation that you recommended above and attempt to drop all rows with null values again. If all rows with null values in any column were dropped, how many rows would be left?

In [14]:
df.dropna()

,Company,TypeName,Inches,screen_resolution,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_brand,cpu_name,cpu_speed,Ram,primary_storage,gpu_brand,gpu_name,OpSys,Weight,Price,total_pixels
9,Acer,Ultrabook,14.0,Full HD,1,0,1080.0,1920,Intel,Core i5,1.6,20.0,256,Intel,UHD Graphics 620,windows,1.6,41026,2073600
19,Dell,Ultrabook,13.3,Full HD,1,1,1080.0,1920,Intel,Core i5,1.6,8.0,128,Intel,UHD Graphics 620,windows,1.2,52161,2073600
20,Lenovo,Gaming,15.6,Full HD,1,0,1080.0,1920,Intel,Core i5,2.5,20.0,128,Nvidia,GeForce GTX 1050,windows,2.5,53227,2073600
22,Dell,2 in 1 Convertible,13.3,Full HD,0,1,1080.0,1920,Intel,Core i5,1.6,20.0,256,Intel,UHD Graphics 620,windows,1.6,43636,2073600
26,Dell,Notebook,15.6,Full HD,0,0,1080.0,1920,Intel,Core i5,1.6,8.0,256,AMD,Radeon 530,windows,2.2,42624,2073600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1312,Lenovo,2 in 1 Convertible,13.3,Quad HD +,1,1,1800.0,3200,Intel,Core i7,2.5,16.0,512,Intel,HD Graphics 520,windows,1.3,79867,5760000
1314,Lenovo,Notebook,13.3,Full HD,1,0,1080.0,1920,Intel,Core i5,2.5,8.0,256,Intel,HD Graphics 620,windows,1.1,53227,2073600
1317,Asus,Notebook,15.6,Full HD,0,0,1080.0,1920,Intel,Core i7,2.7,8.0,256,Intel,HD Graphics 620,windows,2.0,65215,2073600
1318,Lenovo,Ultrabook,15.6,Full HD,0,0,1080.0,1920,Intel,Core i7,2.7,6.0,256,Nvidia,GeForce 920M,windows,1.5,44276,2073600
1321,Dell,Gaming,15.6,Full HD,0,0,1080.0,1920,Intel,Core i7,2.8,40.0,128,Nvidia,GeForce GTX 1050 Ti,windows,2.6,71875,2073600

 Question 11
 
The Company column contains errors. What kind of errors are they?

In [16]:
df['Company'].value_counts()

Company
Dell         192
Lenovo       190
HP           173
Asus         103
hp            83
dell          81
lenovo        81
Acer          64
asus          35
Toshiba       30
MSI           28
msi           25
acer          24
toshiba       15
Apple         15
Samsung        5
samsung        5
apple          4
Xiaomi         4
Vero           4
Razer          4
Chuwi          3
mediacom       3
Google         3
Mediacom       3
Fujitsu        2
LG             2
Microsoft      2
Huawei         2
microsoft      2
razer          2
Name: count, dtype: int64

 Question 12

Fix the error shown above using the method of your preference. You may need to use ChatGPT and/or Google to figure out how to do this (hint: use the .str.title() method).

How many computers in this data set are from the company Apple?

In [17]:
df['Company'] = df['Company'].str.lower()

# Standardize company names
company_mapping = {
    'hp': 'HP',
    'dell': 'Dell',
    'lenovo': 'Lenovo',
    'asus': 'Asus',
    'acer': 'Acer',
    'toshiba': 'Toshiba',
    'msi': 'MSI',
    'apple': 'Apple',
    'samsung': 'Samsung',
    'xiaomi': 'Xiaomi',
    'vero': 'Vero',
    'razer': 'Razer',
    'mediacom': 'Mediacom',
    'google': 'Google',
    'fujitsu': 'Fujitsu',
    'lg': 'LG',
    'microsoft': 'Microsoft',
    'huawei': 'Huawei',
    'chuwi': 'Chuwi'
}

df['Company'] = df['Company'].map(company_mapping)

# Check the standardized counts
print(df['Company'].value_counts())

Company
Dell         273
Lenovo       271
HP           256
Asus         138
Acer          88
MSI           53
Toshiba       45
Apple         19
Samsung       10
Razer          6
Mediacom       6
Microsoft      4
Xiaomi         4
Vero           4
Chuwi          3
Google         3
Huawei         2
Fujitsu        2
LG             2
Name: count, dtype: int64

 Question 13

It's difficult to tell, but some of the laptops seem to have extremely high prices. Use the z-score method with a threshold of 3 to create a filter and determine which laptops are outliers in the data set in terms of price.

Using the outlier detection method from above, how many outliers exist in this data set according to price?

In [21]:
average_price = df['Price'].mean()
std_dev_price = df['Price'].std()

df['Z-Score'] = (df['Price'] - average_price) / std_dev_price

In [24]:
df[df['Z-Score'] > 3]

,Company,TypeName,Inches,screen_resolution,has_ips_panel,is_touchscreen,resolution_width,resolution_height,cpu_brand,cpu_name,cpu_speed,Ram,primary_storage,gpu_brand,gpu_name,OpSys,Weight,Price,total_pixels,Z-Score
189,Razer,Gaming,17.3,4k Ultra HD,0,1,2160.0,3840,Intel,Core i7,2.9,32.0,1024,Nvidia,GeForce GTX 1080,windows,3.5,324955,8294400,5.588091
229,Asus,Gaming,17.3,Full HD,0,0,1080.0,1920,Intel,Core i7,2.9,32.0,512,Nvidia,GeForce GTX 1080,windows,4.7,207259,2073600,3.096261
595,NaN,Notebook,15.6,4k Ultra HD,1,0,2160.0,3840,Intel,Xeon E3-1535M,3.1,32.0,1024,Nvidia,Quadro M2200M,NaN,2.5,261019,8294400,4.234454
673,HP,Workstation,17.3,Full HD,0,0,1080.0,1920,Intel,Core i7,2.8,8.0,500,Nvidia,Quadro M1200,windows,3.1,1016580,2073600,20.230998
727,HP,Workstation,17.3,Full HD,1,0,1080.0,1920,Intel,Xeon E3-1535M,2.9,16.0,256,Nvidia,Quadro M2000M,windows,3.0,233846,2073600,3.659155
765,Dell,Gaming,15.6,Full HD,0,0,1080.0,1920,Intel,Core i5,2.5,8.0,256,Nvidia,GeForce GTX 1050,windows,2.6,524810,2073600,9.819370
806,Razer,Gaming,17.3,4k Ultra HD,0,1,2160.0,3840,Intel,Core i7,2.9,32.0,512,Nvidia,GeForce GTX 1080,windows,3.5,292987,8294400,4.911273
1036,NaN,Gaming,17.3,Full HD,1,0,1080.0,1920,Intel,Core i7,2.7,64.0,1024,Nvidia,GeForce GTX 980,NaN,3.6,211788,2073600,3.192148
1106,HP,Workstation,17.3,Full HD,1,0,1080.0,1920,Intel,Core i7,2.6,8.0,256,Nvidia,Quadro M3000M,windows,3.0,210424,2073600,3.163270

 Question 15

Drop all duplicates from the data set using a subset of the columns Company, cpu_name, gpu_name, total_pixels, and Ram.

How many rows are left in the data set?

In [25]:
df.drop_duplicates(subset=['Company', 'cpu_name', 'gpu_name', 'total_pixels', 'Ram'], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 743 entries, 0 to 1321
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            646 non-null    object
 1   TypeName           743 non-null    object
 2   Inches             743 non-null    float64
 3   screen_resolution  503 non-null    object
 4   has_ips_panel      743 non-null    int64
 5   is_touchscreen     743 non-null    int64
 6   resolution_width   743 non-null    float64
 7   resolution_height  743 non-null    int64
 8   cpu_brand          743 non-null    object
 9   cpu_name           743 non-null    object
 10  cpu_speed          743 non-null    float64
 11  Ram                674 non-null    float64
 12  primary_storage    743 non-null    int64
 13  gpu_brand          743 non-null    object
 14  gpu_name           743 non-null    object
 15  OpSys              615 non-null    object
 16  Weight             705 non-null    float64
 17  Price              743 non-null    int64
 18  total_pixels       743 non-null    int64
 19  Z-Score            743 non-null    float64
dtypes: float64(6), int64(6), object(8)
memory usage: 121.9+ KB